### PR TITLE
example 10

### PR DESCRIPTION
**Pull request by DOSexample**

### CODE REVIEW

**Comment by zombieyang** [comment]
原本的demo我准备保持尽可能简单。能否在projects目录下新开一个项目存放？

**Comment by zombieyang** [comment]
如同#34所说，我后续计划提供 入门-进阶-高级 三个程度的demo，保证PuerTS入门者学习曲线的平滑。

如果你的example更趋向于提供完善的开发体验，正好可用于推进这个计划。

**Comment by DOSexample** [comment]
Yes, You can look here: https://gist.github.com/DOSexample/81249ad2515165f80997262359285ee0

**Comment by zombieyang** [comment]
Sorry I write in English..
I plan to make a new Project located at maybe `projects/AdvancedDemo` to show some more difficult use case. But keep the old demo simple and easy to start quickly.
your commit is very suitable to do this. So could you move your code to another directory in `projects/`?

**Pull request merged**
