### PR TITLE
Puerts using Unity package structure

### PR DESCRIPTION
**Pull request by marwie**
Hello,

I started using puerts recently and am really impressed by it!

This PR moves the puerts code into a [package](https://docs.unity3d.com/Manual/PackagesList.html).
This change has the following benefits:
- it can be more easily shared across multiple Unity projects 
- clear separation between plugin/external code and user/example/project-specific code

The structure proposed is what we are using in all of our projects.

The PR does also make the following changes (let me know if you'd want this to be split into separate PRs instead):
- remove ``*.meta`` file ignore
- add ``.md`` file extension to license file
- ignore generated typescript @types
- add ``ProjectSettings`` and version 

You may have a look at the [dev branch](https://github.com/needle-tools/puerts_unity_demo/tree/dev) where I added another Unity project to the same repo using the shared package to work on additional puerts-unity features

### CODE REVIEW

**Comment by marwie** [comment]
Or should this PR maybe made in the Puerts main repo? Is this a change you would consider making? Would be great to get some feedback, I'd love to help if necessary :)

**Comment by marwie** [comment]
Just noticed that this is one of the [planned changes](https://github.com/Tencent/puerts/projects/1#card-55260065) for puerts anyways :)

**Comment by zombieyang** [comment]
yes, we're planning to do this.
We're considering use [npm](https://npmjs.org) as PackageManager because it is more suitable for jscode.
and use npm hooks to add C# code directory to `Packages/manifest.json`.
it seems that this OpenUPM doing some similar thing?

**Comment by marwie** [comment]
You should be able to store javascript code in a similar fasion on OpenUPM / in one or multiple Unity packages - See [Special folders/Hidden section](https://docs.unity3d.com/Manual/SpecialFolders.html).

Regarding npm for C# maybe you can have a look at [Keijiro's npm packages](https://www.npmjs.com/~keijiro) - he is uploading all his unity packages to npm also.

Regarding OpenUPM vs npm: not sure if there is a benefit in using either - you might even be able to upload to both (I think OpenUPM is generally only Unity devs so it might just be a preference or target audiency type decision).

Whatever you choose I would prefer if I could install and update puerts from within Unity by using their PackageManager to see available versions and updates right away from within the editor. To make that work maybe the package could be structured like so:

package/
- ``package.json`` Unity package json
- ``Runtime/puerts.core.asmdef`` Puerts runtime code
- ``Editor/puerts.core.editor.asmdef`` Puerts editor code
- ``TsProj~/package.json`` typescript package with all the files and a relative filepath for puerts.core dependency like ``file:../Runtime/`` 

I'm wondering: TsProj is not necessary to use puerts but merely used as a demo, right? So should it be even shipped with the package like that? If you want to provide example maybe a better solution would be to include it as a [Sample](https://docs.unity3d.com/Manual/cus-samples.html)?

**Comment by zombieyang** [comment]
thanks for your suggestion.

Yes TsProj is a demo and it's not necessary to put into puerts.core package.
I think `04_ConsoleRedirect` and `03_NodeTSCAndHotReload ` rather than `puerts.core` are more suitable for considering the case: 'design a package layout for the packages with both JS and C# code'.
The reason I want to use npm is that some tools like `webpack` or `rollup` can easily combine many npm js package(in `node_modules`) to one js file. PuerTS can just load the generated js file and no need to solve the dependecies in `ILoader`. If we put JS code into directory with `~`, I'll afraid about developers may spend too much work to write their Loader.
Maybe it's different from what Keijiro do.

-------------------------
Besides I think we can put `puerts.core` to OpenUPM、Unity PackageManager、npm first. Just using the layout you mentioned above. I think it is perfect.

**Comment by marwie** [comment]
Btw something related because you mention hot reload and ILoader: in my experiments I have had both Typescript and C# components in one packages (actually even besides each other) and did use a ScriptedImporter to recompile the puerts component on the fly whenever the typescript changed. This allowed me to have hot reload both in editor at edit time as well as at runtime. 

Additionally I also added some functionality to export the typescript code on build-time to the StreamingAssets folder and added loaders that handle hot reload in builds. Tested in standalone windows only tho. I guess you have a lot of similar functionality already but maybe still interesting for you as well? It is all in the [dev branch here](https://github.com/needle-tools/puerts_unity_demo/tree/dev) if you're curious (open the ``projects/Puets_2020_3`` project)

**Comment by zombieyang** [comment]
Sorry I was spent my timefor a urgent feature this week. Back to this issue today :).

I've read your `ts-sample`. It's nice. Do you consider to publish it as a UPM package? I think I can translate a 中文 doc for you after you publish it as a UPM package (I think it's helpful because most of the puerts developer are using 中文 since now)

I try to upload a OpenUPM package but I fail. I submit my test repository in this page: https://openupm.com/packages/add/. But it return 403 and it's said that github API rate limit exceeded. Could you give me some advice?

**Comment by zombieyang** [comment]
Sorry I was spent my time for an urgent feature this week. Back to this issue today :).

I've read your `ts-sample`. It's nice. Do you consider to publish it as a UPM package? I think I can translate a 中文 doc for you after you publish it as a UPM package (I think it's helpful because most of the puerts developer are using 中文 since now)

I made a UPM branch for puerts today. And I need to submit a PR to openupm repository to add my package on it, right? It make me feel a little bit strange.

**Comment by marwie** [comment]
No worries! :)

Yes, did you add it via this form [https://openupm.com/packages/add](https://openupm.com/packages/add/) ? I'd suggest to convert this (or another) repository to the package format and then submit it. 

One really nice thing about OpenUPM is that you make updates just by adding a new tag to your repo (in a certain format that you have to define in the yaml, e.g. release/1.0.1) so devs can then just pull the new version via Unity's PackageManager :)

**Pull request merged**
